paths:
  public: "public"
groups:
  scripts:
    paths:
      - app/scripts
    concat:
      "/scripts/app.js": "app/**/*.{js,coffee}"
      "/scripts/vendor.js": "vendor/**/*.{js,coffee}"
    order:
      - vendor/jquery-1.10.2.js
      - ...
      - app/scripts/app.coffee
  styles:
    paths:
      - app/styles
    concat:
      "/styles/app.css": "{app,vendor}/**/[a-z]*.{css,scss,sass}"
  images:
    paths:
      - app/images
    sprite:
      "../app/styles/icons.scss": "app/images/**/*.png"
  views:
    paths:
      - app/views
    copy:
      "/": "app/views/**/*.{hbs,html}"
  templates:
    paths:
      - app/templates
    precompile:
      "../vendor/templates.js": "{app/templates/**/*.hbs,app/components/**/*.hbs}"
  components:
    paths:
      - app/components
modules:
  wrapper: cmd
  ignored: vendor/**/*
  definition: /scripts/app.js
sprites:
  url: /images/
  path: /images/
  selector: .icon-
revision:
  files:
    - index.html
notification: true
bundles:
  jquery.js:
    version: 1.10.2
    url: http://code.jquery.com/jquery-1.10.2.js
  handlebars.js:
    version: 1.0.0
    url: https://raw.github.com/wycats/handlebars.js/1.0.0/dist/handlebars.runtime.js
  pokeball.js:
    version: master
    url: http://git.terminus.io:9099/terminus/pokeball/raw/master/public/pokeball.js
  essage.js:
    version: 0.1.0
    url: https://raw.githubusercontent.com/sofish/essage/master/src/essage.js
  essage.css:
    version: 0.1.0
    url: https://raw.githubusercontent.com/sofish/essage/master/src/essage.css
